### ISSUE TITLE
New Option

### ISSUE THREAD

**Issue by fatalcoder524** [ribomation/firestore-transfer#2]
Open to give custom document name. it can be a fixed string or a list from import.json.!!!

**Comment by fatalcoder524** [comment]
Found a way to give custom document name. Thanks for this wonderful code.

**Comment by ribomation** [comment]
When you import a document, you can choose if it's a list or an object. In the former case docs gets push-ids, in the latter the key will be the ids

**Comment by ribomation** [comment]
let me know if that was what you meant
